### ISSUE TITLE
source(here(code_dir, "utils.R"))

### ISSUE THREAD

**Issue by luminwin** [bdwilliamson/vimp_supplementary#1]
Dear Brian, When I run get_vimp.R, I have the following error at the beginning. Can you help me with that? Thank you!
library("SuperLearner")
library("dplyr")
library("argparse")
library("here")

lib_paths <- .libPaths()
# require vimp@v2.2.3 or higher
if (is.na(Sys.getenv("RSTUDIO", unset = NA))) {
    library("vimp", lib.loc = lib_paths[2])
    code_dir <- ""
} else {
    library("vimp")
    code_dir <- "code"
}

> source(here(code_dir, "utils.R"))

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/Users/min/Documents/VarPro/code/utils.R': No such file or directory

**Comment by bdwilliamson** [comment]
Thanks for catching this typo -- I hadn't updated some of the directory structure in this repo to match the initial repo I used to run the code. 

You'll want to make sure you're running this code (e.g., if you are using an R project) from within `vimp_supplementary` so that `here` can find the appropriate files.

This should be fixed in e96370b, but let me know if you have further issues.
